//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aep_project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_FREQ_DIM
    {
        public decimal RPT_FREQ_ID { get; set; }
        public string RPT_FREQ_NAME { get; set; }
        public Nullable<System.DateTime> LAST_UPDT_DTTM { get; set; }
        public string LAST_UPDT_ID { get; set; }
    }
}
