//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aep_project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORECARD_PHOTO_FACT
    {
        public decimal CATEGORY_ID { get; set; }
        public decimal DATE_ID { get; set; }
        public decimal MEASURE_ID { get; set; }
        public byte[] EMPLOYEE_PHOTO { get; set; }
    }
}
